language: go
sudo: false
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip
script:
  - go get -u golang.org/x/lint/golint
  - OUT="$(go get -a)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - OUT="$(gofmt -l -d ./)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - OUT="$(golint ./...)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - go vet -v ./...
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./
  - go build
after_success:
  - bash <(curl -s https://codecov.io/bash)
